# Generated by Django 4.2.3 on 2023-07-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
